[user]
name = "alice pellerin"
email = "thealicepellerin@gmail.com"

[ui]
default-command = "log"
log-word-wrap = false
pager = "less --quit-if-one-screen"
diff-editor = ":builtin"
merge-editor = ":builtin"

[revsets]
log = "ancestors(@::, 4):: | ancestors(present(main)::, 2):: | ancestors(present(master)::, 2)::"

[signing]
behavior = "own"
backend = "gpg"

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"
"closest_pushable(to)" = "heads(::to & mutable() & ~description(\"\") & ~empty())"

[aliases]
tug = ["bookmark", "move", "--from", "closest_bookmark(@)", "--to", "closest_pushable(@)"]
