[user]
name = "alice pellerin"
email = "thesimonpellerin@gmail.com"

[ui]
default-command = "log"
log-word-wrap = false
pager = "less --quit-if-one-screen --RAW-CONTROL-CHARS --incsearch --ignore-case"

[revsets]
log = "ancestors(@::, 4):: | ancestors(present(main)::, 2):: | ancestors(present(master)::, 2)::"
