interface = "en1"

memory_percentage = true

disks = ["/"]
disk_space_percentage = true

show = ["Host", "Machine", "Kernel", "OperatingSystem", "Packages", "Shell", "Terminal", "LocalIP", "Resolution", "Uptime", "Processor", "ProcessorLoad", "Memory", "DiskSpace"]

