"$schema" = "https://starship.rs/config-schema.json"

format = "${custom.directory}${custom.directory_linux}$status$character"
right_format = "$cmd_duration$git_metrics$package$hostname$time"

add_newline = false

[character]
format = "$symbol"
success_symbol = "[❯](bright-white)"
error_symbol = "[❯](red)"

[cmd_duration]
format = "[⏱ $duration]($style) "
style = "bright-white"
min_time = 500
show_milliseconds = true

[custom.directory]
format = "$output"
shell = "/Users/simonomi/Documents/swift/custom-directory-prompt/custom directory prompt"
when = true
os="macos"

[custom.directory_linux]
format = "$output"
shell = "/home/simonomi/custom-directory-prompt/custom directory prompt"
when = true
os="linux"

[git_metrics]
disabled = false

[hostname]
format = "[$ssh_symbol$hostname]($style) "
ssh_symbol = " "

[package]
format = "[$symbol$version]($style) "
symbol = "󰏗 "

[status]
format = "[\\[$status\\]]($style)"
disabled = false

[time]
format = "[$time]($style)"
time_format = "%H:%M"
style = "bright-black"
disabled = false

