"ui.background" = "light-grey"
"ui.cursor" = { bg = "light-grey" }
"ui.cursor.match" = { bg = "select-grey" }
"ui.cursor.primary.select" = { bg = "yellow" }
"ui.gutter.selected" = { bg = "dark-grey" }
"ui.linenr" = "light-grey"
"ui.linenr.selected" = { fg = "yellow", modifiers = ["bold"] }

"ui.statusline" = { fg = "white", bg = "ui-grey" }
"ui.statusline.inactive" = { fg = "light-grey", bg = "ui-grey" }
"ui.statusline.normal" = { fg = "black", bg = "blue" }
"ui.statusline.insert" = { fg = "black", bg = "green" }
"ui.statusline.select" = { fg = "black", bg = "yellow" }

"ui.bufferline" = { bg = "ui-grey" }
"ui.bufferline.active" = { bg = "select-grey" }
"ui.bufferline.background" = { bg = "black" }

"ui.popup" = { bg = "dark-grey" }
"ui.help" = { bg = "dark-grey" }

"ui.text" = "white"
"ui.text.focus" = { bg = "grey" }
"ui.text.inactive" = "grey"

"ui.virtual.whitespace" = { fg = "dark-grey" }
"ui.virtual.jump-label" = { fg = "blue", modifiers = ["bold", "underlined"] }

"ui.menu" = { fg = "white", bg = "dark-grey" }
"ui.menu.selected" = { modifiers = ["reversed"] }

"ui.selection" = { bg = "select-grey" }

error = "203"
warning = "yellow"
info = "blue"
hint = "light-grey"
diagnostic = { bg = "blue" }
# "diagnostic.error" = { fg = "black", bg = "203" }
"diagnostic.error" = { bg = "dark-grey" }
# "diagnostic.warning" = { fg = "black", bg = "yellow" }
"diagnostic.warning" = { bg = "dark-grey" }
# "diagnostic.info" = { fg = "black", bg = "blue" }
"diagnostic.info" = { bg = "dark-grey" }
"diagnostic.hint" = { bg = "dark-grey" }

# attribute
type = "blue"
"type.builtin" = "blue"
constructor = "light-magenta"
constant = "light-magenta"
"constant.numeric" = "light-yellow"
string = "light-red"
comment = "grey"
variable = "81"
"variable.builtin" = "light-magenta"
label = "light-magenta"
# punctuation
keyword = "light-magenta"
"keyword.directive" = "yellow"
# operator
function = "green"
"function.macro" = "yellow" # used for #if in swift
# tag
# namespace
special = "cyan"

"markup.heading" = "light-blue"
"markup.list" = "light-yellow"
"markup.bold" = { fg = "light-cyan", modifiers = ["bold"] }
"markup.italic" = { fg = "light-magenta", modifiers = ["italic"] }
"markup.strikethrough" = { fg = "light-grey", modifiers = ["crossed_out"] }
"markup.link" = "81"
"markup.link.text" = "light-cyan"
"markup.quote" = "light-grey"
"markup.raw" = "light-grey"

"diff.plus.gutter" = "green"
"diff.minus.gutter" = "red"
"diff.delta.gutter" = "blue"

[palette]
grey = "#6C7986"
dark-grey = "8"
ui-grey = "238"
select-grey  = "242"
light-grey = "7"
